version: "2"

services:
  mariadb:
    image: "docker.io/bitnami/mariadb:10.2-debian-10"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=pizza-task
      - MARIADB_PASSWORD=my_password
    networks:
      - internal

  pizza-task-api:
    tty: true
    image: docker.io/bitnami/laravel:7-debian-10
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=pizza-task
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    networks:
      - nginx_network
      - internal
    # privileged: true # Privileged mode could be required to run this container under Windows

networks:
  nginx_network:
    driver: bridge
  internal:
